site_name: SCMPGUI Documentation

repo_url: https://github.com/cepdnaclk/e19-co227-subclinical-mastitis-prediction-gui
repo_name: cepdnaclk/e19-co227-subclinical-mastitis-prediction-gui

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono

extra:
  homepage: https://cepdnaclk.github.io/e19-co227-subclinical-mastitis-prediction-gui/
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cepdnaclk/e19-co227-subclinical-mastitis-prediction-gui
    - icon: fontawesome/solid/globe
      link: https://cepdnaclk.github.io/e19-co227-subclinical-mastitis-prediction-gui/

