name: Django Automated Testing

on:
  push:
    branches:
      - main  
  pull:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django testing
      run: |
      python manage.py test results
    